from pathlib import Path

from rulescope.eve import correlate_alerts, parse_eve_file
from rulescope.pipeline import build_catalog, load_profile, make_disable_conf
from rulescope.parser import parse_rules_file

ROOT = Path(__file__).resolve().parents[1]
RULES = ROOT / "samples" / "rules" / "demo.rules"
PROFILE = ROOT / "samples" / "profiles" / "homelab.json"
EVE = ROOT / "samples" / "eve" / "eve-alerts.json"


def test_parse_demo_rules():
    rules = parse_rules_file(RULES)
    assert len(rules) >= 8
    sids = {r.sid for r in rules}
    assert 202141773 in sids
    assert 202500100 in sids


def test_enrich_and_relevance():
    profile = load_profile(PROFILE)
    rules, summary = build_catalog([RULES], profile)
    assert summary.total_rules >= 8
    assert summary.with_cve >= 2
    by_sid = {r.sid: r for r in rules}
    apache = by_sid[202141773]
    assert "CVE-2021-41773" in apache.cves
    assert apache.severity in {"high", "critical", "medium"}
    assert apache.relevance_score > 40
    scada = by_sid[202500100]
    assert scada.relevance_label in {"low", "noise", "medium"}
    assert scada.relevance_score < apache.relevance_score


def test_disable_export_contains_noise():
    text = make_disable_conf([RULES], load_profile(PROFILE), max_score=40)
    assert "Generated by RuleScope" in text
    assert "202500100" in text or "2014901" in text


def test_eve_correlation():
    rules, _ = build_catalog([RULES], load_profile(PROFILE))
    views = correlate_alerts(parse_eve_file(EVE), rules)
    assert len(views) == 4
    mapped = [v for v in views if v.rule is not None]
    assert len(mapped) == 4
    assert mapped[0].rule.cves
