"""Export suricata-update compatible enable/disable configs."""

from __future__ import annotations

from rulescope.models import EnrichedRule


def render_disable_conf(rules: list[EnrichedRule], *, header: str | None = None) -> str:
    lines = [
        "# Generated by RuleScope — https://github.com/abdulrafay-123/rulescope",
        "# Compatible with suricata-update disable.conf",
        header or "# Candidates: low relevance / noise / outdated for your asset profile",
        "",
    ]
    for rule in rules:
        reason = ", ".join(rule.relevance_reasons[:3]) or rule.relevance_label
        msg = rule.msg.replace("\n", " ")[:80]
        lines.append(f"# SID {rule.sid} score={rule.relevance_score} [{rule.relevance_label}] {msg}")
        lines.append(f"# reason: {reason}")
        lines.append(str(rule.sid))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_enable_conf(rules: list[EnrichedRule], *, header: str | None = None) -> str:
    lines = [
        "# Generated by RuleScope — https://github.com/abdulrafay-123/rulescope",
        "# Compatible with suricata-update enable.conf",
        header or "# High-relevance rules to keep enabled",
        "",
    ]
    for rule in rules:
        msg = rule.msg.replace("\n", " ")[:80]
        lines.append(f"# SID {rule.sid} score={rule.relevance_score} [{rule.severity}] {msg}")
        lines.append(str(rule.sid))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def rules_to_dicts(rules: list[EnrichedRule]) -> list[dict]:
    return [r.model_dump(mode="json") for r in rules]
